export {
	calculationSections,
	coveringTypes,
	floorProducts,
	getBaseTypesByCovering,
	getMaterialNamesBySection,
	getSoilDilutionByMaterial,
	glueBrands,
	glueCoverings,
	glueFloorBases,
	glueTrowels,
	materialNames,
	soilBaseTypes,
	soilDilutions,
	soilProducts,
} from "./mock-options";
export type {
	FloorBaseOption,
	FloorProductOption,
	GlueBrandOption,
	GlueConsumptionRule,
	MaterialOption,
	MockOption,
	SoilProductOption,
} from "./mock-options";
